version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.14
    working_directory: /go/src/github.com/aita/dnscache
    steps:
      - checkout
      - run: go mod download
      - run: go test -v -race ./...
